ALTER TABLE `Order`
  ADD COLUMN IF NOT EXISTS `address` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `city` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `pincode` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `state` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `countryCode` VARCHAR(191) NULL;
