export const RAW_MASTER_DATA = {
  roles: ["admin", "sales", "production", "dispatch"],
  enquiryStatuses: ["PENDING", "ACCEPTED", "REJECTED"],
  orderStatuses: ["CREATED", "IN_PRODUCTION", "READY_FOR_DISPATCH", "PARTIALLY_DISPATCHED", "COMPLETED", "DISPATCHED"],
  productionStatuses: ["PENDING", "IN_PROGRESS", "PARTIALLY_PRODUCED", "HOLD", "COMPLETED"],
  shipmentStatuses: ["PACKING", "SHIPPED", "DELIVERED"],
  units: ["KG", "MT", "LTR"],
  modeOfEnquiry: ["Phone", "Whatsapp", "Website", "We Reached Out", "Walk-in", "Other"],
  assignedPersons: [
    "Sharun Mittal",
    "Saumya Mittal",
    "Ravishu Mittal",
    "Ankesh Jain",
    "Shrinivas Potukuchi"
  ],
  supervisors: [
    "Vaibhav Mishra",
    "Amarjeet",
    "Ankit",
    "Sonu Mahur",
    "Omprakash",
    "Satish Singh",
    "Mandeep Singh"
  ],
  companyNames: [],
  products: [
    "ALUMINIUM STEARATE",
    "ANTIBLOCKING AGENT",
    "BARIUM STEARATE",
    "Butyl Stearate",
    "CALCIUM 12-HYDROXY STEARATE",
    "CALCIUM STEARATE",
    "CALCIUM ZINC STABILIZER",
    "Calcium Zinc Stearate",
    "Cetyl-Stearyl Alcohols",
    "EGDS",
    "GMS 40",
    "GMS 90",
    "GMS 95",
    "GMS 97",
    "HSA 12 MAGNESIUM STEARATE",
    "Isostearic Acid",
    "Lithium 12-Hydroxystearate",
    "Lithium Stearate",
    "MAGNESIUM STEARATE",
    "Manganese Stearate",
    "Neutral Polymer",
    "NIMAID EBS",
    "NIMLUB - 187",
    "NIMLUB - T",
    "NIMLUB CZ 50",
    "NIMLUB NR6",
    "NIMPHOB",
    "NIMSTAT N66",
    "NUWAX",
    "OXO-BIODEGRADABLE ADDITIVE",
    "PE WAX",
    "PE WAX-500",
    "Pentaerythritol Tetrastearate (PETS)",
    "Potassium Octadecanoate",
    "Sodium Benzoate",
    "Sodium Octadecanoate",
    "STEARIC ACID",
    "TALC",
    "Ultra 8100",
    "ZINC 12-HYDROXY STEARATE",
    "Zinc Laurate",
    "ZINC OXIDE",
    "Zinc salt of fatty acids",
    "ZINC STEARATE",
    "Zinc Stearate",
    "ABC"
  ],
  countryCodes: ["IN"],
  finishedGoodsCatalog: [
    "Zinc Stearate",
    "Zinc Stearate (Paper)",
    "Calcium Stearate",
    "Calcium Stearate (Paper)",
    "Magnesium Stearate",
    "Magnesium Stearate (Paper)",
    "Manganese Stearate",
    "CZ-100",
    "CZ-100 (Paper)",
    "PE-Wax",
    "Calcium Stearate LD",
    "Sima-100N",
    "Nimlub-T",
    "Aluminium Stearate",
    "GMS"
  ],
  rawMaterialsCatalog: [
    "Stearic Acid",
    "Zinc Oxide",
    "Calcium Hydroxide",
    "Magnesium Oxide",
    "Magnesium Hydroxide",
    "PE-Wax",
    "Calcium Carbonate Coated",
    "Calcium Carbonate Uncoated",
    "Soapstone",
    "M-Acid",
    "Liquid Additive",
    "Acetic Acid",
    "Magacler",
    "KINOX-1010",
    "Radios Tab",
    "Holtac",
    "Titanium di-oxide",
    "Zeolite",
    "Caustic Soda Flakes",
    "EBS"
  ],
  packingMaterialsCatalog: [
    "Zinc Stearate Trans. Bag",
    "Calcium Stearate Trans. Bag",
    "Magnesium Stearate Trans. Bag",
    "Magnesium Stearate 12HSA Trans. Bag",
    "CZ-100-83 Trans. Bag",
    "CZ-100-85 Trans. Bag",
    "ZN. Haldia Trans. Bag",
    "Cal. Haldia Trans. Bag",
    "Aluminium Stearate Trans. Bag",
    "Zinc Stearate (PPT) Bags",
    "PE-Wax Trans. Bag",
    "White Plain Bag",
    "CS-1001 Trans. Bag",
    "Product Code Trans. Bag",
    "Ultra-8000 Trans. Bag",
    "GMS Trans. Bag",
    "Zinc Oxide Trans. Bag",
    "Jumbo Bag (Flat)",
    "Jumbo Bag (Open mouth)",
    "Liner (Bundle) Primary Packing",
    "Zinc Stearate Paper Bag",
    "Calcium Stearate Paper Bag",
    "Magnesium Stearate Paper Bag",
    "CZ-100 Paper Bag",
    "Unprinted Paper Bag",
    "Printed Paper Bag",
    "Sima-100N Paper Bag",
    "Magnesium Stearate 12HSA Paper Bag",
    "Zinc Oxide Paper Bag",
    "PE-Wax Paper Bag",
    "White Paper Bag",
    "Brown Paper Bag",
    "Wood Pallets (43x43)",
    "Wood Pallets (37x37)",
    "Cartoon",
    "Cartoon Small",
    "IBC Tank",
    "Empty Drum 200ltr",
    "Empty Can 50ltr"
  ]
};

function toOptions(values) {
  return values.map((value) => ({ value, label: String(value) }));
}

const PRODUCTION_STATUS_OPTIONS = [
  { value: "PENDING", label: "Not Started" },
  { value: "IN_PROGRESS", label: "In Progress" },
  { value: "PARTIALLY_PRODUCED", label: "Partially Produced" },
  { value: "HOLD", label: "Hold" },
  { value: "COMPLETED", label: "Completed" }
];

const SHIPMENT_STATUS_OPTIONS = [
  { value: "PACKING", label: "Packed" },
  { value: "SHIPPED", label: "Dispatched" },
  { value: "DELIVERED", label: "Delivered" }
];

export const MASTER_DATA = {
  roles: toOptions(RAW_MASTER_DATA.roles),
  enquiryStatuses: toOptions(RAW_MASTER_DATA.enquiryStatuses),
  orderStatuses: toOptions(RAW_MASTER_DATA.orderStatuses),
  productionStatuses: PRODUCTION_STATUS_OPTIONS,
  shipmentStatuses: SHIPMENT_STATUS_OPTIONS,
  units: toOptions(RAW_MASTER_DATA.units),
  modeOfEnquiry: toOptions(RAW_MASTER_DATA.modeOfEnquiry),
  assignedPersons: toOptions(RAW_MASTER_DATA.assignedPersons),
  supervisors: toOptions(RAW_MASTER_DATA.supervisors),
  companyNames: toOptions(RAW_MASTER_DATA.companyNames),
  products: toOptions(RAW_MASTER_DATA.products),
  countryCodes: toOptions(RAW_MASTER_DATA.countryCodes),
  finishedGoodsCatalog: toOptions(RAW_MASTER_DATA.finishedGoodsCatalog),
  rawMaterialsCatalog: toOptions(RAW_MASTER_DATA.rawMaterialsCatalog),
  packingMaterialsCatalog: toOptions(RAW_MASTER_DATA.packingMaterialsCatalog)
};

export default MASTER_DATA;
export const MASTER_DATA_CATEGORIES = Object.freeze(Object.keys(MASTER_DATA));
